### ISSUE TITLE
Build failiure

### ISSUE THREAD

**Issue by williamsmj** [jakevdp/PythonicPerambulations#7]
This is almost certainly something very simple (e.g. a missing dependency), but I'm getting a build failure when running `pelican content` on a fresh copy of this repository. Suggestions very welcome!

```
$ pelican content
WARNING: pelicanconf.py:73: UserWarning: _nb_header.html not found.  Rerun make html to finalize build.
  warnings.warn("_nb_header.html not found.  "

WARNING: PLUGIN_PATH setting has been replaced by PLUGIN_PATHS, moving it to the new setting name.
WARNING: Defining PLUGIN_PATHS setting as string has been deprecated (should be a list)
WARNING: Feeds generated without SITEURL set properly may not be valid
Traceback (most recent call last):
  File "/Users/mike/.virtualenvs/ds/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/Users/mike/.virtualenvs/ds/lib/python2.7/site-packages/pelican/__init__.py", line 351, in main
    pelican, settings = get_instance(args)
  File "/Users/mike/.virtualenvs/ds/lib/python2.7/site-packages/pelican/__init__.py", line 345, in get_instance
    return cls(settings), settings
  File "/Users/mike/.virtualenvs/ds/lib/python2.7/site-packages/pelican/__init__.py", line 57, in __init__
    signals.initialized.send(self)
  File "/Users/mike/.virtualenvs/ds/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "pelican-plugins/liquid_tags/liquid_tags.py", line 12, in addLiquidTags
    gen.settings['MD_EXTENSIONS'].append(LiquidTags(configs))
  File "/Users/mike/.virtualenvs/ds/lib/python2.7/site-packages/markdown/extensions/__init__.py", line 28, in __init__
    self.setConfigs(args[0])
  File "/Users/mike/.virtualenvs/ds/lib/python2.7/site-packages/markdown/extensions/__init__.py", line 76, in setConfigs
    self.setConfig(key, value)
  File "/Users/mike/.virtualenvs/ds/lib/python2.7/site-packages/markdown/extensions/__init__.py", line 64, in setConfig
    if isinstance(self.config[key][0], bool):
KeyError: 'settings'
[ds] ~/tmp/PythonicPerambulations master
```

This is based on a clean clone of this repo (i.e. these are the only commands I run immediately before I get the above error):

```
$ git clone git@github.com:jakevdp/PythonicPerambulations.git
Cloning into 'PythonicPerambulations'...
remote: Counting objects: 751, done.
remote: Total 751 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (751/751), 20.92 MiB | 1.78 MiB/s, done.
Resolving deltas: 100% (387/387), done.
Checking connectivity... done.
[ds] ~/tmp 
$ cd PythonicPerambulations/
drwxr-xr-x  2 mike   68 Jan 25 03:19 pelican-plugins/
drwxr-xr-x  2 mike   68 Jan 25 03:19 pelican-octopress-theme/
-rwxr-xr-x  1 mike 1865 Jan 25 03:19 develop_server.sh*
drwxr-xr-x 54 mike 1836 Jan 25 03:19 content/
-rw-r--r--  1 mike   20 Jan 25 03:19 TODO.txt
-rw-r--r--  1 mike  690 Jan 25 03:19 README.md
-rw-r--r--  1 mike 3087 Jan 25 03:19 Makefile
[ds] ~/tmp/PythonicPerambulations master
$ git submodule init
Submodule 'pelican-octopress-theme' (git@github.com:jakevdp/pelican-octopress-theme.git) registered for path 'pelican-octopress-theme'
Submodule 'pelican-plugins' (git@github.com:getpelican/pelican-plugins.git) registered for path 'pelican-plugins'
[ds] ~/tmp/PythonicPerambulations master
$ git submodule update
Cloning into 'pelican-octopress-theme'...
remote: Counting objects: 653, done.
remote: Compressing objects: 100% (319/319), done.
remote: Total 653 (delta 325), reused 653 (delta 325)
Receiving objects: 100% (653/653), 191.31 KiB | 0 bytes/s, done.
Resolving deltas: 100% (325/325), done.
Checking connectivity... done.
Submodule path 'pelican-octopress-theme': checked out 'd90ff392f63980e26c9d33d38903b3e0ab5fe6af'
Cloning into 'pelican-plugins'...
remote: Counting objects: 2148, done.
remote: Total 2148 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (2148/2148), 1.25 MiB | 646.00 KiB/s, done.
Resolving deltas: 100% (917/917), done.
Checking connectivity... done.
Submodule path 'pelican-plugins': checked out 'a2dc0d44c0ecddeee804ef04a2855789b2efc9ed'
```

**Comment by jakevdp** [comment]
I don't know what ``pelican content`` is supposed to do, but every time I run ``make`` it works fine.

Also potentially relevant: I use Pelican 3.3 and a bunch of other older packages, because things keep changing in pelican & markdown & IPython and other dependencies, and I don't have the time to try and track down all the interactions that are changing. So that may be why it's not working for you.

**Comment by jakevdp** [comment]
If you're looking for suggestions, I'd say blog with Nikola instead of Pelican. They seem to have a much more integrated interface for things like IPython notebook.

**Comment by williamsmj** [comment]
I think `pelican content` is effectively a frontend for `make html`, at least in this context.

Unfortunately `make html` results in the same error. Thanks anyway for taking a look!
